"""add_owner_id_to_files_folders

Revision ID: 423efa013cf2
Revises: 0468414f2f58
Create Date: 2026-07-10 18:13:07.330097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423efa013cf2'
down_revision: Union[str, Sequence[str], None] = '0468414f2f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files') as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_id', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key('fk_files_owner_id_users', 'users', ['owner_id'], ['id'])
    with op.batch_alter_table('folders') as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_folders_owner_id_users', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders') as batch_op:
        batch_op.drop_constraint('fk_folders_owner_id_users', type_='foreignkey')
        batch_op.drop_column('owner_id')
    with op.batch_alter_table('files') as batch_op:
        batch_op.drop_constraint('fk_files_owner_id_users', type_='foreignkey')
        batch_op.drop_column('team_id')
        batch_op.drop_column('owner_id')
    # ### end Alembic commands ###
