"""add_owner_id_to_files_folders

Revision ID: 423efa013cf2
Revises: 0468414f2f58
Create Date: 2026-07-10 18:13:07.330097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423efa013cf2'
down_revision: Union[str, Sequence[str], None] = '0468414f2f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('team_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'files', 'users', ['owner_id'], ['id'])
    op.add_column('folders', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'folders', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_column('folders', 'owner_id')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'team_id')
    op.drop_column('files', 'owner_id')
    # ### end Alembic commands ###
