"""Backward-compatible re-exports from domain-specific schema modules.

All classes are now defined in individual modules (auth.py, file.py, etc.)
and re-exported here so that `from app.domain.schemas import X` continues to work.
"""

from app.domain.auth import (
    AuthResponse,
    CurrentUserResponse,
    LoginRequest,
    RefreshTokenRequest,
    UserCreate,
    UserPublic,
    UserUpdate,
)
from app.domain.common import (
    AuditLogEntry,
    AuditLogResponse,
    DashboardSummary,
    ErrorResponse,
    NotificationItem,
    NotificationListResponse,
    NotificationType,
    PermissionAction,
    PermissionEffect,
    PermissionResourceType,
    PermissionRuleCreate,
    PermissionRuleListResponse,
    PermissionRulePublic,
    PermissionSubjectType,
    WorkspaceSnapshot,
)
from app.domain.file import (
    FileAnnotationCreate,
    FileAnnotationItem,
    FileAnnotationListResponse,
    FileAnnotationReplyCreate,
    FileAnnotationReplyItem,
    FileCopyRequest,
    FileContentResponse,
    FileContentUpdate,
    FileItem,
    FileListResponse,
    FileUpdate,
    FileVersionItem,
    FileVersionListResponse,
    MultipartChunkResponse,
    MultipartUploadInitRequest,
    MultipartUploadSession,
    MultipartUploadStatus,
    CompressionRequest,
    CompressionResult,
    RecycleBinItem,
    RecycleBinResponse,
    ShareLinkCreateRequest,
    ShareLinkDownloadRequest,
    ShareLinkPublic,
)
from app.domain.folder import (
    FolderCreate,
    FolderItem,
    FolderTreeResponse,
    FolderUpdate,
)
from app.domain.knowledge import (
    Citation,
    KnowledgeBaseCreate,
    KnowledgeBaseListResponse,
    KnowledgeBasePublic,
    KnowledgeBaseStatus,
    KnowledgeBaseUpdate,
    KnowledgeConversationDetailResponse,
    KnowledgeConversationListResponse,
    KnowledgeConversationPublic,
    KnowledgeDocumentCreate,
    KnowledgeDocumentListResponse,
    KnowledgeDocumentPublic,
    KnowledgeFileBatchRequest,
    KnowledgeFileBatchResponse,
    KnowledgeFreshnessPolicy,
    KnowledgeIndexStatus,
    KnowledgeMessagePublic,
    KnowledgeScopeType,
    QARequest,
    QAResponse,
)
from app.domain.team import (
    TeamCreate,
    TeamDetail,
    TeamInviteCreate,
    TeamInvitePublic,
    TeamInviteStatus,
    TeamListResponse,
    TeamMemberJoin,
    TeamMemberPublic,
    TeamMemberStatus,
    TeamMemberUpdate,
    TeamMessageCreate,
    TeamMessageItem,
    TeamMessageListResponse,
    TeamMessageType,
    TeamRole,
    TeamSummary,
    TeamUpdate,
)
from app.domain.workflow import (
    AgentStep,
    AgentTaskContinueRequest,
    AgentTaskRequest,
    AgentTaskResponse,
    ToolDefinition,
    ToolListResponse,
    WorkflowCreate,
    WorkflowDefinition,
    WorkflowEdgeDefinition,
    WorkflowExecutionRequest,
    WorkflowExecutionResponse,
    WorkflowListResponse,
    WorkflowNodeDefinition,
    WorkflowNodeExecution,
    WorkflowNodeType,
    WorkflowUpdate,
    WorkflowValidationIssue,
    WorkflowValidationResponse,
)
